// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUo0Ebnjn0sGOUEDmaRzsq8IwFj_mlhzY',
    appId: '1:110533283142:web:af3f920cdc677949796947',
    messagingSenderId: '110533283142',
    projectId: 'bd-biblioteca-pi3-lef',
    authDomain: 'bd-biblioteca-pi3-lef.firebaseapp.com',
    storageBucket: 'bd-biblioteca-pi3-lef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdmUU0y4iblrOsph8BexusMA1HhKSxDfA',
    appId: '1:110533283142:android:7ab7d4dcdb580d70796947',
    messagingSenderId: '110533283142',
    projectId: 'bd-biblioteca-pi3-lef',
    storageBucket: 'bd-biblioteca-pi3-lef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwT28puikyUV0zLKMfVwtXQ-RchCS9xZA',
    appId: '1:110533283142:ios:fd5668debd9bf929796947',
    messagingSenderId: '110533283142',
    projectId: 'bd-biblioteca-pi3-lef',
    storageBucket: 'bd-biblioteca-pi3-lef.appspot.com',
    iosBundleId: 'com.example.bibliotecaUniceuAlvarenga',
  );
}
